
server:
  port: 8082

aps:
  base-url: http://localhost:8080/activiti-app/api

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/activiti
    username: alfresco
    password: alfresco
  main:
    web-application-type: reactive
  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/activiti
    username: alfresco
    password: alfresco
  application:
    name: system_monitoring

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


  web:
    reactive:
      pathpattern:
        cache:
          size: 1024
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/aps-realm
          jwk-set-uri: http://localhost:8085/realms/aps-realm/protocol/openid-connect/certs
